# Generated by Django 3.0.1 on 2020-01-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeyDo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='task',
            field=models.CharField(max_length=300),
        ),
    ]
