# Generated by Django 3.0.1 on 2019-12-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeyDo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
